[package]
name = "taiko-untitled"
version = "0.1.0"
authors = ["seasellsheshell"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = { version = "0.34.2", features = ["image", "ttf"] }
config = "0.10.1"
# stainless_ffmpeg = "0.2.0"
# stainless-ffmpeg-sys = "4.2.2-update.1"
ffmpeg4 = { git = "https://github.com/TonalidadeHidrica/rust-ffmpeg4", branch = "fix-missing-variable" }
byteorder = "1.3.4"
itertools = "0.9.0"
# ffmpeg-next = {git = "https://github.com/zmwangx/rust-ffmpeg"}
