[package]
name = "taiko-untitled"
version = "0.1.0"
authors = ["seasellsheshell"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.3.4"
config = "0.10.1"
ffmpeg4 = { git = "https://github.com/TonalidadeHidrica/rust-ffmpeg4", branch = "fix-missing-variable" }
itertools = "0.10.2"
sdl2 = { version = "0.35.2", features = ["image", "ttf"] }

# stainless_ffmpeg = "0.2.0"
# stainless-ffmpeg-sys = "4.2.2-update.1"
# ffmpeg-next = {git = "https://github.com/zmwangx/rust-ffmpeg"}
