[package]
name = "taiko-untitled"
version = "0.1.0"
authors = ["seasellsheshell"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.115", features = ["derive"] }
config = "0.10.1"
encoding_rs = "0.8.24"
chardetng = "0.1.9"
itertools = "0.9.0"
num = "0.3.0"
cpal = "0.13.2"
retain_mut = "0.1.1"
enum-map = "0.6.3"
ordered-float = "2.0.0"
boolinator = "2.4.0"
derive_more = "0.99.11"
once_cell = "1.5.2"
regex = "1.4.2"

sdl2 = { version = "0.34.4", features = ["image"], path = "../rust-sdl2" }
sdl2-sys = { version = "0.34.3", path = "../rust-sdl2/sdl2-sys/" }

rodio = { version = "0.13.0", path = "../rodio" }
universal-audio-decoder = { path = "../universal-audio-decoder/" }
notify = "4.0.15"
